mode: daemonset

config:
  exporters:
    otlp:
      endpoint: ingest.splunk.com:4317
      headers:
        "X-SF-TOKEN": "<SPLUNK_ACCESS_TOKEN>"
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp]
