version: "3.7"
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme123
    ports:
      - "8000:8000"
      - "8088:8088"
      - "9997:9997"
    volumes:
      - splunk-data:/opt/splunk/var
volumes:
  splunk-data:

